### ISSUE TITLE
White elements and weird things

### ISSUE THREAD

**Issue by MaXfAa** [aidanhorton/ecosia-darkmode-extensions#33]
There are some persistent white elements:
![image](https://user-images.githubusercontent.com/71935156/170725721-c09701d7-6d07-44ff-9e8c-6ea397b47d58.png)

URL: https://www.ecosia.org/search?q=baudelaire+les+fleurs+du+mal
But look at the blank and black Wikipedia image in this screenshot (on the right).

Now, look at this one:
This time, the image blank image is white... 🤔 

![image](https://user-images.githubusercontent.com/71935156/170726381-e00e6fe5-f27c-4a8f-975a-44caafc4688e.png)
URL: https://www.ecosia.org/search?q=baudelaire+les+fleurs+du+mal+contexte+d%27%C3%A9criture

**Comment by OppnedKatt** [comment]
The white colour on the Shopping-tab may be fixed already, but is still not released. I can't really test it as I don't get the Shopping-tab my self. Aidan may have to look at that. 

As for the fallback-image, I have find a way of fixing it, but I'm not sure on if the current white should be transparent or a lighter gray.

**Comment by aidanhorton** [comment]
Apologies I didn't get a notification for this! Like OppnedKatt says, the shopping tab should be fixed hopefully quite soon by the work in progress branch! As for the cards at the top of the search results, I'll make sure that's fixed in the next update too!
And the blank images, we'll look into that too! 

I would estimate 1-2 weeks for resolution 😊

**Comment by OppnedKatt** [comment]
But should the blank images be transparent or a lighter gray?

**Comment by aidanhorton** [comment]
> But should the blank images be transparent or a lighter gray?

@OppnedKatt probably worth trying both, but based-on the image on the right-hand-side in the image above, transparent looks like it would be quite a slick solution! But if that's not possible to get working, then lighter gray is the next best alternative :)

**Comment by OppnedKatt** [comment]
I tried both earlier. I'll commit the changes when I get the opportunity.

**Comment by OppnedKatt** [comment]
I'll just leave two images of it here:
![bilde](https://user-images.githubusercontent.com/68151654/171053242-d66cf44a-e8b8-4077-88bf-14acef712f38.png)
![bilde](https://user-images.githubusercontent.com/68151654/171053292-f51cd1bd-b721-4f4b-b24a-58964580ad4e.png)

**Comment by OppnedKatt** [comment]
I have committed some stuff a few minutes ago now. Again, I can't look at the ads myself.

**Comment by aidanhorton** [comment]
@MaXfAa @OppnedKatt the work that was in progress has been merged in (thanks to Oppned for fixing!). It should be approved by Chrome + FireFox by the end of today.
Let me know if these issues persist, and if I hear nothing back in the next 2 weeks or so I'll mark this issue as closed 😄

**Comment by aidanhorton** [comment]
Due to the new Ecosia update, and the PR https://github.com/aidanhorton/ecosia-darkmode-extensions/pull/38 that went in to fix it - these issues are non-existent, and have been fixed as a side-effect of that work, ontop of the fact that they were already fixed by another PR :)
So I'll mark this issue as closed!
